module.exports = {
  projects: [
    '<rootDir>/packages/core',
    '<rootDir>/packages/core/materials',
    '<rootDir>/packages/core/geometries',
    '<rootDir>/packages/core/meshes',
    '<rootDir>/packages/core/lights',
    '<rootDir>/packages/core/loaders',
    '<rootDir>/packages/core/stats',
    '<rootDir>/packages/controls',
    '<rootDir>/packages/core/attributes',
    '<rootDir>/packages/postprocessing',
    '<rootDir>/packages/postprocessing/render-pass',
    '<rootDir>/packages/core/canvas',
    '<rootDir>/packages/postprocessing/ssao-pass',
    '<rootDir>/packages/postprocessing/unreal-bloom-pass',
    '<rootDir>/packages/postprocessing/shader-pass',
    '<rootDir>/packages/core/group',
    '<rootDir>/packages/core/scene',
    '<rootDir>/packages/loaders',
    '<rootDir>/packages/loaders/gltf-loader',
    '<rootDir>/packages/core/audios',
    '<rootDir>/packages/core/sprites',
    '<rootDir>/packages/core/lod',
  ],
};
