export enum ThreeImports {
  WebGLRenderTarget = 'THREE.WebGLRenderTarget',
  ShaderMaterial = 'THREE.ShaderMaterial',
  MeshDepthMaterial = 'THREE.MeshDepthMaterial',
  Color = 'THREE.Color',
  Mesh = 'THREE.Mesh',
  CubeTexture = 'THREE.CubeTexture',
  Scene = 'THREE.Scene',
  PerspectiveCamera = 'THREE.PerspectiveCamera',
  DataTexture = 'THREE.DataTexture',
  DataTexture3D = 'THREE.DataTexture3D',
  Camera = 'THREE.Camera',
  Object3D = 'THREE.Object3D',
  Vector2 = 'THREE.Vector2',
  Texture = 'THREE.Texture',
  MeshBasicMaterial = 'THREE.MeshBasicMaterial',
  Matrix4 = 'THREE.Matrix4',
  MeshNormalMaterial = 'THREE.MeshNormalMaterial',
  Vector3 = 'THREE.Vector3',
  WebGLRenderer = 'THREE.WebGLRenderer',
  TextureEncoding = 'THREE.TextureEncoding',
  MeshStandardMaterial = 'THREE.MeshStandardMaterial',
}
