// Use Buffer version to also include normal version
export const geometries = [
  'BufferGeometry',
  'InstancedBufferGeometry',
  'BoxBufferGeometry',
  'CircleBufferGeometry',
  'ConeBufferGeometry',
  'CylinderBufferGeometry',
  'DodecahedronBufferGeometry',
  'ExtrudeBufferGeometry',
  'IcosahedronBufferGeometry',
  'LatheBufferGeometry',
  'OctahedronBufferGeometry',
  'PlaneBufferGeometry',
  'PolyhedronBufferGeometry',
  'RingBufferGeometry',
  'ShapeBufferGeometry',
  'SphereBufferGeometry',
  'TetrahedronBufferGeometry',
  'TorusBufferGeometry',
  'TorusKnotBufferGeometry',
  'TubeBufferGeometry',
  'WireframeGeometry',
  'EdgesGeometry',
];

export const exampleGeometries = [
  'BoxLineGeometry',
  'ConvexGeometry',
  'DecalGeometry',
  'ParametricGeometry',
  'RoundedBoxGeometry',
  'TeapotGeometry',
  'TextGeometry',
];
