// Use Buffer version to also include normal version
export const geometries = [
  'InstancedBufferGeometry',
  'BoxBufferGeometry',
  'CircleBufferGeometry',
  'ConeBufferGeometry',
  'CylinderBufferGeometry',
  'DodecahedronBufferGeometry',
  'ExtrudeBufferGeometry',
  'IcosahedronBufferGeometry',
  'LatheBufferGeometry',
  'OctahedronBufferGeometry',
  'ParametricBufferGeometry',
  'PlaneBufferGeometry',
  'PolyhedronBufferGeometry',
  'RingBufferGeometry',
  'ShapeBufferGeometry',
  'SphereBufferGeometry',
  'TetrahedronBufferGeometry',
  'TextBufferGeometry',
  'TorusBufferGeometry',
  'TorusKnotBufferGeometry',
  'TubeBufferGeometry',
  'WireframeGeometry',
  'EdgesGeometry',
];
