// GENERATED
export const additionalSobaShapesSelectors = [
  'soba-plane',
  'soba-box',
  'soba-cylinder',
  'soba-cone',
  'soba-circle',
  'soba-sphere',
  'soba-tube',
  'soba-torus',
  'soba-tetrahedron',
  'soba-ring',
  'soba-polyhedron',
  'soba-octahedron',
  'soba-dodecahedron',
  'soba-icosahedron',
  'soba-extrude',
  'soba-lathe',
  'soba-parametric',
  'soba-torus-knot',
];
