import type { ControlCollection } from '../models/control-collection.model';

export const controls: ControlCollection = [
  {
    name: 'ArcballControls',
    injectDocument: false,
    importThree: false,
    useRenderer: true,
    useScene: true,
    inputs: [],
    constructor: '(camera, renderer.domElement, scene)',
  },
  {
    name: 'OrbitControls',
    injectDocument: false,
    importThree: false,
    useRenderer: true,
    useScene: false,
    inputs: [],
    constructor: '(camera, renderer.domElement)',
  },
  {
    name: 'FlyControls',
    injectDocument: false,
    importThree: false,
    useRenderer: true,
    useScene: false,
    inputs: [],
    constructor: '(camera, renderer.domElement)',
  },
  {
    name: 'FirstPersonControls',
    injectDocument: false,
    importThree: false,
    useRenderer: true,
    useScene: false,
    inputs: [],
    constructor: '(camera, renderer.domElement)',
  },
  {
    name: 'PointerLockControls',
    injectDocument: true,
    importThree: false,
    useRenderer: false,
    useScene: false,
    inputs: [],
    constructor: '(camera, this.document.body)',
  },
  {
    name: 'DragControls',
    injectDocument: false,
    importThree: true,
    useRenderer: true,
    useScene: false,
    inputs: [
      {
        name: 'objects',
        import: 'THREE.Object3D',
        isOptional: false,
        isArray: true,
        default: '[]',
      },
    ],
    constructor: '(this.objects, camera, renderer.domElement)',
  },
  {
    name: 'TrackballControls',
    injectDocument: false,
    importThree: false,
    useRenderer: true,
    useScene: false,
    inputs: [],
    constructor: '(camera, renderer.domElement)',
  },
  {
    name: 'TransformControls',
    injectDocument: false,
    importThree: false,
    useRenderer: true,
    useScene: false,
    inputs: [],
    constructor: '(camera, renderer.domElement)',
  },
];
