export const INPUTS = [
    'ref',
    'attach',
    'skipWrapper',
    'skipInit',
    'noAttach',
    'beforeRender',
    'priority',
    'updateCallback',
    'readyCallback',
];

export const OUTPUTS = [
    'click',
    'contextmenu',
    'dblclick',
    'pointerup',
    'pointerdown',
    'pointerover',
    'pointerout',
    'pointerenter',
    'pointerleave',
    'pointermove',
    'pointermissed',
    'pointercancel',
    'wheel',
];

export const OBJECT_3D_INPUTS = [
    'name',
    'position',
    'rotation',
    'quaternion',
    'scale',
    'modelViewMatrix',
    'normalMatrix',
    'matrix',
    'matrixWorld',
    'matrixAutoUpdate',
    'matrixWorldAutoUpdate',
    'matrixWorldNeedsUpdate',
    'layers',
    'visible',
    'castShadow',
    'receiveShadow',
    'frustumCulled',
    'renderOrder',
    'animations',
    'userData',
    'customDepthMaterial',
    'customDistanceMaterial',
    'onBeforeRender',
    'onAfterRender',
];
